// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFgsQpfg75Nbz_SbSGhhppFcH12ep4WuA',
    appId: '1:99676277612:web:92ec8ec3d45f883337c149',
    messagingSenderId: '99676277612',
    projectId: 'flutterfire-ui-auth-629f1',
    authDomain: 'flutterfire-ui-auth-629f1.firebaseapp.com',
    storageBucket: 'flutterfire-ui-auth-629f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrp-mch6gmaUAeN5BO6S-F-trr6_9IqQ0',
    appId: '1:99676277612:android:12f749864003fcc437c149',
    messagingSenderId: '99676277612',
    projectId: 'flutterfire-ui-auth-629f1',
    storageBucket: 'flutterfire-ui-auth-629f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYBZwdCtXF6CuS1-4HNRiGh9EgyWPl0Pw',
    appId: '1:99676277612:ios:d6e448aef80f820e37c149',
    messagingSenderId: '99676277612',
    projectId: 'flutterfire-ui-auth-629f1',
    storageBucket: 'flutterfire-ui-auth-629f1.appspot.com',
    iosClientId: '99676277612-mljn4babvug3if8m4dd92t0074chhqv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
